config/routes.rb
Rails.application.routes.draw do
  get 'user_inputs/create'
  get 'user_inputs/update'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'assmats/refresh', to: 'assmats#refresh'
  resources :assmats, only: [:index, :show]
  resources :user_inputs, only: [:index, :show, :create, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assmat.rb
class Assmat < ApplicationRecord
  has_many :availabilities, dependent: :destroy
  has_many :user_inputs, dependent: :destroy
  has_many :users, through: :user_inputs

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/availability.rb
class Availability < ApplicationRecord
  belongs_to :assmat
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_inputs, dependent: :destroy
  has_many :assmats, through: :user_inputs
end

app/models/user_input.rb
class UserInput < ApplicationRecord
  belongs_to :assmat
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/assmats_controller.rb
class AssmatsController < ApplicationController
  PREFIX = 'https://assmat.loire-atlantique.fr/'.freeze

  def index
    @assmats = Assmat.all.order(:distance)
    @user = current_user
    @markers = make_markers

    @user_inputs = {}
    Assmat.joins(:user_inputs).each do |assmat|
      ui = UserInput.find_by(user: @user, assmat: assmat)
      @user_inputs[assmat] = ui
    end
  end

  def patch_comment

  end

  def refresh
    Availability.delete_all
    Assmat.delete_all
    import_from_web

    pp @assmats

    redirect_to assmats_path
  end

  private

  def make_markers
    # the `geocoded` scope filters only flats with coordinates (latitude & longitude)
    @assmats.geocoded.map do |assmat|
      {
        lat: assmat.latitude,
        lng: assmat.longitude,
        infoWindow: render_to_string(partial: "shared/info_window", locals: { assmat: assmat })
      }
    end
  end

  def import_from_web
    page = 0
    loop do
      attributes = { start: page * 10 }
      call(attributes)
      # There is no information about being on the last page or not.
      # If we go loop until page 1000, the server will keep serving the last X results for each page we request
      break if @assmat.name != Assmat.last.name # not very safe if the last page has exactly 10 results
      break if page >= 16 # guard clause
      page += 1
    end
  end

  def call(attributes = { start: 0 })
    @url = "https://assmat.loire-atlantique.fr/jcms/parents/faire-une-recherche-d-assistante-maternelle-fr-r1_58176?idCommune=rp1_62646&codeInsee=44109&cities=44036&longitude=-1.56512&latitude=47.219901&cityName=Nantes&adresse=#{ENV['ADDRESS_TO_SEARCH']}&distance=3000&month=1617200000000&age=1%7C17%7C2%7C3%7C10%7C15%7C16%7C19&branchesId=cra_67000&branchesId=cra_67001&branchesId=&nomassmat=&isSearch=Ok&hashKey=88&withDispo=true&withDispoFuture=true&withNonDispo=false&withDispoNonRenseigne=false&start=#{attributes[:start]}"

    html_file = URI.parse(@url).open.read
    html_doc  = Nokogiri::HTML(html_file)

    html_doc.search('.amcontainer').each do |amcontainer|
      data1   = amcontainer.search('.row-fluid')[0]
      data2   = amcontainer.search('.row-fluid')[1]

      @assmat = Assmat.new
      parse_data1(data1)
      break if Assmat.select(:name).map(&:name).include?(@assmat.name)

      parse_data2(data2)
      @assmat.save!
      parse_subpage(@assmat.url)
      # binding.pry
      pp Assmat.select(:name).map(&:name), (@assmat.name)

      pp @assmat
    end
    @assmat
  end

  def parse_data1(data1)
    @assmat.name        = data1.at_css('h2').text.strip
    @assmat.last_update = data1.at_css('p').text.strip[-10..-1]
    quartier            = data1.at_css('.quartier')
    @assmat.area        = quartier ? quartier.text.strip[11..-1].split(' ').join(' ') : 'quartier inconnu'
    @assmat.distance    = data1.text.strip.match(/à (?<dist>.{1,4}) km/)[:dist].gsub(',', '.').to_f
  end

  def parse_data2(data2)
    regexp2         = /((?<address>.*) (Tél fixe : (?<phone>(\d)+)) Tél portable: (?<cell>.*) Courriel (?<available>.*) En savoir plus|(?<address>.+) Tél portable: (?<cell>.+) Courriel (?<available>.*) En savoir plus)/
    data2_text      = data2.text.split.join(' ')
    contact_details = data2_text.match(regexp2) || {} # empty hash if nil
    @assmat.address = contact_details[:address] || ''
    @assmat.phone   = contact_details[:phone] || 'NC'
    @assmat.cell    = contact_details[:cell] || 'NC'
    @assmat.general_availability = contact_details[:available] || 'NC'
    # pp @assmat

    @assmat.url = "#{PREFIX}#{data2.search('.wysiwyg a').attribute('href').value}"
  end

  def parse_subpage(url)
    html_file = URI.parse(url).open.read

    li = Nokogiri::HTML(html_file).css('.listeDispos li')
    li.each_with_index do |dispo, index|
      next unless (index % 3).zero? # after each li with data, there are 2 lis with nothing interesting

      # get availability details
      cr_dispo        = dispo.at_css('p.crDispos') ? dispo.at_css('p.crDispos').text.strip : 'NC'
      precision_dispo = if dispo.at_css('div.precisionDispo p')
                          dispo.at_css('div.precisionDispo p').text.strip.gsub(',', '-')
                        else
                          'Pas de précision'
                        end
      # get the full calendar, which is a big table of avail/not available timeslots.
      creneau_dispo = '|'
      dispo.search('tr td img').each_with_index do |creneau, index_creneau|
        if index_creneau.even? # I can't make the search precise enough so I have to eliminate some cr*ppy tag
          creneau_dispo << (creneau['class'] == 'creneauNonDispo' ? '-' : 'X')
        end
        creneau_dispo << '|' if (creneau_dispo.size % 8).zero?
      end

      availability = Availability.new(
        assmat: @assmat,
        description: cr_dispo,
        details: precision_dispo,
        calendar: creneau_dispo,
      )
      availability.save!
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  
  def home
    redirect_to assmats_path
  end
end

app/controllers/user_inputs_controller.rb
class UserInputsController < ApplicationController
  def create
    @assmat = Assmat.find(params[:assmat])
    @user = current_user

    UserInput.create!(assmat: @assmat, user: @user, comment: "", selected: false)

    redirect_to assmats_path

  end

  def update
    @user_input = UserInput.find(params[:id])
    @user_input.update(user_input_params)

    redirect_to assmats_path
  end

  private

  def user_input_params
    params.require(:user_input).permit(:comment, :selected)
  end

  def user_input_assmat_params
    params.require(:assmat).permit(:id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/assmats/index.html.erb
<div class="container">
  <div id="map"
    style="width: 100%; height: 600px;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

  <table class= "table">
    <% @assmats.each do |assmat| %>
    <tr>
      <td><%= assmat.name %></td>
      <td><%= assmat.address %></td>
      <td><%= assmat.distance %></td>
      <td>
        <% if @user_inputs[assmat] %>
          <div class="user-input">
            <div class="read">
              <span><%= @user_inputs[assmat].comment %></span><br>
              <a href="" class="edit-comment" data-assmat-id="<%= assmat.id %>">edit</a>
            </div>
            <div class="write hidden">
              <%= simple_form_for [@user_inputs[assmat]], remote: true do |f| %>
              <%= f.input :comment %>
              <%= f.input :selected, label: "En favoris" %>
              <%= f.submit "Update" %>
              <% end %>
            </div>
          </div>
        <% else %>
          <%= link_to "new", user_inputs_create_path(assmat: assmat) %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BAM - BetterAssMat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_info_window.html.erb
<h3><%= assmat.name %></h3>
<p><%= assmat.address %></p>
<%= link_to "details", assmat.url %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/user_inputs/create.html.erb
<h1>UserInputs#create</h1>
<p>Find me in app/views/user_inputs/create.html.erb</p>

app/views/user_inputs/update.html.erb
<h1>UserInputs#update</h1>
<p>Find me in app/views/user_inputs/update.html.erb</p>
<%= @user_input.comment %>
<%= @user_input.selected %>